# .github/workflows/email-test.yml
name: Email Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 23f3000543@ds.study.iitm.ac.in
        run: echo "Hello, world!"
